#██████╗░███████╗██████╗░░██╗░░░░░░░██╗░█████╗░██████╗░░██████╗░░░░░░██╗░░░██╗██╗░░░░░████████╗██████╗░░█████╗░
#██╔══██╗██╔════╝██╔══██╗░██║░░██╗░░██║██╔══██╗██╔══██╗██╔════╝░░░░░░██║░░░██║██║░░░░░╚══██╔══╝██╔══██╗██╔══██╗
#██████╦╝█████╗░░██║░░██║░╚██╗████╗██╔╝███████║██████╔╝╚█████╗░█████╗██║░░░██║██║░░░░░░░░██║░░░██████╔╝███████║
#██╔══██╗██╔══╝░░██║░░██║░░████╔═████║░██╔══██║██╔══██╗░╚═══██╗╚════╝██║░░░██║██║░░░░░░░░██║░░░██╔══██╗██╔══██║
#██████╦╝███████╗██████╔╝░░╚██╔╝░╚██╔╝░██║░░██║██║░░██║██████╔╝░░░░░░╚██████╔╝███████╗░░░██║░░░██║░░██║██║░░██║
#╚═════╝░╚══════╝╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░░░░░░░░╚═════╝░╚══════╝░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚═╝

Verison: 1.0


Scoreboard:
  Title: "&7-=-=&e&lBEDWARS&7=-=-"
  lines:
  - "     <date>"
  - ""
  - " &f&l▶ &a&lᴘʟᴀʏᴇʀ ◀"
  - "  &f| Level: &a<level>"
  - "  &f| Progress: &a<progess>"
  - "  &f| <progressbar>"
  - ""
  - " &f&l▶ &b&lꜱᴛᴀᴛꜱ ◀"
  - "  &f| Kills: &b<kills>"
  - "  &f| Wins: &b<wins>"
  - ""
  - "    &bmc.bedwars.com"
  
Citizens:
  Solo:
    ID:
    location:
    Hologram:
  Double:
    ID:
    location:
    Hologram:
  Trios:
    ID:
    location:
    Hologram:
  Quad:
    ID:
    location:
    Hologram:
  Groups:
    ID:
    location:
    Hologram:
