#██████╗░███████╗██████╗░░██╗░░░░░░░██╗░█████╗░██████╗░░██████╗░░░░░░██╗░░░██╗██╗░░░░░████████╗██████╗░░█████╗░
#██╔══██╗██╔════╝██╔══██╗░██║░░██╗░░██║██╔══██╗██╔══██╗██╔════╝░░░░░░██║░░░██║██║░░░░░╚══██╔══╝██╔══██╗██╔══██╗
#██████╦╝█████╗░░██║░░██║░╚██╗████╗██╔╝███████║██████╔╝╚█████╗░█████╗██║░░░██║██║░░░░░░░░██║░░░██████╔╝███████║
#██╔══██╗██╔══╝░░██║░░██║░░████╔═████║░██╔══██║██╔══██╗░╚═══██╗╚════╝██║░░░██║██║░░░░░░░░██║░░░██╔══██╗██╔══██║
#██████╦╝███████╗██████╔╝░░╚██╔╝░╚██╔╝░██║░░██║██║░░██║██████╔╝░░░░░░╚██████╔╝███████╗░░░██║░░░██║░░██║██║░░██║
#╚═════╝░╚══════╝╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░░░░░░░░╚═════╝░╚══════╝░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚═╝

Verison: 1.0


Scoreboard:
  Title: ""
